// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: protobufs/sijl/sijl.proto

package psijl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SijlClient is the client API for Sijl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SijlClient interface {
	Register(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type sijlClient struct {
	cc grpc.ClientConnInterface
}

func NewSijlClient(cc grpc.ClientConnInterface) SijlClient {
	return &sijlClient{cc}
}

func (c *sijlClient) Register(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/sijl.Sijl/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sijlClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/sijl.Sijl/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SijlServer is the server API for Sijl service.
// All implementations must embed UnimplementedSijlServer
// for forward compatibility
type SijlServer interface {
	Register(context.Context, *NewUserRequest) (*LoginResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedSijlServer()
}

// UnimplementedSijlServer must be embedded to have forward compatible implementations.
type UnimplementedSijlServer struct {
}

func (UnimplementedSijlServer) Register(context.Context, *NewUserRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSijlServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSijlServer) mustEmbedUnimplementedSijlServer() {}

// UnsafeSijlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SijlServer will
// result in compilation errors.
type UnsafeSijlServer interface {
	mustEmbedUnimplementedSijlServer()
}

func RegisterSijlServer(s grpc.ServiceRegistrar, srv SijlServer) {
	s.RegisterService(&Sijl_ServiceDesc, srv)
}

func _Sijl_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SijlServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sijl.Sijl/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SijlServer).Register(ctx, req.(*NewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sijl_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SijlServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sijl.Sijl/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SijlServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sijl_ServiceDesc is the grpc.ServiceDesc for Sijl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sijl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sijl.Sijl",
	HandlerType: (*SijlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Sijl_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Sijl_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobufs/sijl/sijl.proto",
}
